metadata:
    id: hello-kbner
    language: swe

import:
    importer: text_import:parse

xml_export:
    annotations:
        - <sentence>
        - <token:word>
        - <token>:stanza.pos
        - <token>:sparv_kb_ner.kb-ne

sparv:
    compression: none
